/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import ec.edu.intsuperior.config.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuar
 */
public class Empleados extends javax.swing.JFrame {
   Conexion con1= new Conexion();
Connection conet;
DefaultTableModel modelo;
Statement st;
ResultSet rs;
int idc;
    private Object Tabla;

    /**
     * Creates new form empleados
     */
    public Empleados() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registroempleados = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ingresarempleado = new javax.swing.JTextField();
        IdEmpleados = new javax.swing.JLabel();
        cedula = new javax.swing.JLabel();
        ingrecedula = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        INgresarnombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        Ingresarapellido = new javax.swing.JTextField();
        Seguro = new javax.swing.JLabel();
        ingresarseguro = new javax.swing.JTextField();
        Cargo = new javax.swing.JLabel();
        Ingresarcargo = new javax.swing.JTextField();
        ingresar = new javax.swing.JButton();
        GUARDAR = new javax.swing.JButton();
        ACTUALIZAR = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registroempleados.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        registroempleados.setForeground(new java.awt.Color(255, 255, 255));
        registroempleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroempleados.setText("Registro Empleados");
        getContentPane().add(registroempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 340, 50));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, -1));

        ingresarempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarempleadoActionPerformed(evt);
            }
        });
        getContentPane().add(ingresarempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 500, 20));

        IdEmpleados.setBackground(new java.awt.Color(51, 255, 255));
        IdEmpleados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IdEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        IdEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IdEmpleados.setText("IDEmpleados");
        getContentPane().add(IdEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 20));

        cedula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cedula.setForeground(new java.awt.Color(255, 255, 255));
        cedula.setText("Cédula");
        getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 60, 20));
        getContentPane().add(ingrecedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 500, 20));

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 60, 20));
        getContentPane().add(INgresarnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 500, 20));

        Apellido.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Apellido.setForeground(new java.awt.Color(255, 255, 255));
        Apellido.setText("Apellido");
        getContentPane().add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 60, 20));
        getContentPane().add(Ingresarapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 500, 20));

        Seguro.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Seguro.setForeground(new java.awt.Color(255, 255, 255));
        Seguro.setText("Seguro");
        getContentPane().add(Seguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 70, 20));
        getContentPane().add(ingresarseguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 500, 20));

        Cargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cargo.setForeground(new java.awt.Color(255, 255, 255));
        Cargo.setText("Cargo");
        getContentPane().add(Cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 70, 20));
        getContentPane().add(Ingresarcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 500, 20));

        ingresar.setBackground(new java.awt.Color(51, 255, 0));
        ingresar.setText("INGRESAR");
        getContentPane().add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 90, 50));

        GUARDAR.setBackground(new java.awt.Color(102, 0, 255));
        GUARDAR.setText("GUARDAR");
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });
        getContentPane().add(GUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 90, 50));

        ACTUALIZAR.setBackground(new java.awt.Color(0, 51, 255));
        ACTUALIZAR.setText("ACTUALIZAR");
        getContentPane().add(ACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 90, 50));

        Eliminar.setBackground(new java.awt.Color(255, 0, 0));
        Eliminar.setText("ELIMINAR");
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 90, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleados.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 780, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarempleadoActionPerformed

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUARDARActionPerformed

//    /**
//     * @param args the command line arguments
//     */
        public static void main(String[] args) {
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACTUALIZAR;
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel Cargo;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton GUARDAR;
    private javax.swing.JTextField INgresarnombre;
    private javax.swing.JLabel IdEmpleados;
    private javax.swing.JTextField Ingresarapellido;
    private javax.swing.JTextField Ingresarcargo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Seguro;
    private javax.swing.JLabel cedula;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField ingrecedula;
    private javax.swing.JButton ingresar;
    private javax.swing.JTextField ingresarempleado;
    private javax.swing.JTextField ingresarseguro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel registroempleados;
    // End of variables declaration//GEN-END:variables
}
