/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author usuar
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form productos
     */
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        colocarproductos = new javax.swing.JTextField();
        productos = new javax.swing.JLabel();
        PrecioUnitario = new javax.swing.JLabel();
        ingrepreciounitario = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        INgresarnombre = new javax.swing.JTextField();
        Tipoalcohol = new javax.swing.JLabel();
        Ingresartipodealcohol = new javax.swing.JTextField();
        porcentaje = new javax.swing.JLabel();
        Ingresarporcentaje = new javax.swing.JTextField();
        ingresar = new javax.swing.JButton();
        GUARDAR = new javax.swing.JButton();
        ACTUALIZAR = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 410, 70));
        getContentPane().add(colocarproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 380, 20));

        productos.setBackground(new java.awt.Color(51, 255, 255));
        productos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productos.setForeground(new java.awt.Color(255, 0, 0));
        productos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productos.setText("IDProductos");
        getContentPane().add(productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 80, 20));

        PrecioUnitario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PrecioUnitario.setForeground(new java.awt.Color(255, 0, 0));
        PrecioUnitario.setText("Precio Unitario");
        getContentPane().add(PrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 110, 20));
        getContentPane().add(ingrepreciounitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 380, 20));

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 0, 0));
        Nombre.setText("Nombre");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 60, 20));
        getContentPane().add(INgresarnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 380, 20));

        Tipoalcohol.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Tipoalcohol.setForeground(new java.awt.Color(255, 0, 0));
        Tipoalcohol.setText("Tipo Alcohol");
        getContentPane().add(Tipoalcohol, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 90, 20));
        getContentPane().add(Ingresartipodealcohol, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 380, 20));

        porcentaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        porcentaje.setForeground(new java.awt.Color(255, 0, 0));
        porcentaje.setText("Porcentaje");
        getContentPane().add(porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 80, 20));
        getContentPane().add(Ingresarporcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 380, -1));

        ingresar.setBackground(new java.awt.Color(51, 255, 0));
        ingresar.setText("INGRESAR");
        getContentPane().add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 90, 50));

        GUARDAR.setBackground(new java.awt.Color(102, 0, 255));
        GUARDAR.setText("GUARDAR");
        getContentPane().add(GUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 90, 50));

        ACTUALIZAR.setBackground(new java.awt.Color(0, 51, 255));
        ACTUALIZAR.setText("ACTUALIZAR");
        getContentPane().add(ACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 90, 50));

        Eliminar.setBackground(new java.awt.Color(255, 0, 0));
        Eliminar.setText("ELIMINAR");
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 90, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productoss.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
//     * @param args the command line arguments
//     */
    public static void main(String args[]) {
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACTUALIZAR;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton GUARDAR;
    private javax.swing.JTextField INgresarnombre;
    private javax.swing.JTextField Ingresarporcentaje;
    private javax.swing.JTextField Ingresartipodealcohol;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel PrecioUnitario;
    private javax.swing.JLabel Tipoalcohol;
    private javax.swing.JTextField colocarproductos;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField ingrepreciounitario;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel porcentaje;
    private javax.swing.JLabel productos;
    // End of variables declaration//GEN-END:variables
}
