/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author usuar
 */
public class Proveedores extends javax.swing.JFrame {

    /**
     * Creates new form proveedores
     */
    public Proveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        ColocarProveedor = new javax.swing.JTextField();
        IdProveedores = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        IngresarCorreo = new javax.swing.JTextField();
        Ruc = new javax.swing.JLabel();
        ingresarruc = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        INgresarnombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        Ingresarapellido = new javax.swing.JTextField();
        Direccion = new javax.swing.JLabel();
        ingresardireccion = new javax.swing.JTextField();
        telefono = new javax.swing.JLabel();
        Ingresarteléfono = new javax.swing.JTextField();
        ingresar = new javax.swing.JButton();
        GUARDAR = new javax.swing.JButton();
        ACTUALIZAR = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Ingresoproveedores = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ColocarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 400, 20));

        IdProveedores.setBackground(new java.awt.Color(51, 255, 255));
        IdProveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IdProveedores.setForeground(new java.awt.Color(255, 255, 255));
        IdProveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IdProveedores.setText("IDProveedores");
        getContentPane().add(IdProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 20));

        Correo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Correo.setForeground(new java.awt.Color(255, 255, 255));
        Correo.setText("Correo");
        getContentPane().add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 50, 20));
        getContentPane().add(IngresarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 400, -1));

        Ruc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ruc.setForeground(new java.awt.Color(255, 255, 255));
        Ruc.setText("Ruc");
        getContentPane().add(Ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 60, 20));
        getContentPane().add(ingresarruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 400, 20));

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 60, 20));
        getContentPane().add(INgresarnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 400, 20));

        Apellido.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Apellido.setForeground(new java.awt.Color(255, 255, 255));
        Apellido.setText("Apellido");
        getContentPane().add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 60, 20));
        getContentPane().add(Ingresarapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 400, 20));

        Direccion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Direccion.setForeground(new java.awt.Color(255, 255, 255));
        Direccion.setText("Dirección");
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 70, 20));
        getContentPane().add(ingresardireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 400, 20));

        telefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telefono.setForeground(new java.awt.Color(255, 255, 255));
        telefono.setText("Teléfono");
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 70, 20));
        getContentPane().add(Ingresarteléfono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 400, -1));

        ingresar.setBackground(new java.awt.Color(51, 255, 0));
        ingresar.setText("INGRESAR");
        getContentPane().add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 90, 50));

        GUARDAR.setBackground(new java.awt.Color(102, 0, 255));
        GUARDAR.setText("GUARDAR");
        getContentPane().add(GUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 90, 50));

        ACTUALIZAR.setBackground(new java.awt.Color(0, 51, 255));
        ACTUALIZAR.setText("ACTUALIZAR");
        getContentPane().add(ACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 90, 50));

        Eliminar.setBackground(new java.awt.Color(255, 0, 0));
        Eliminar.setText("ELIMINAR");
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 90, 50));

        Ingresoproveedores.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Ingresoproveedores.setForeground(new java.awt.Color(255, 255, 255));
        Ingresoproveedores.setText("Ingreso De Proveedores");
        getContentPane().add(Ingresoproveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 450, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedores.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACTUALIZAR;
    private javax.swing.JLabel Apellido;
    private javax.swing.JTextField ColocarProveedor;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Direccion;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton GUARDAR;
    private javax.swing.JTextField INgresarnombre;
    private javax.swing.JLabel IdProveedores;
    private javax.swing.JTextField IngresarCorreo;
    private javax.swing.JTextField Ingresarapellido;
    private javax.swing.JTextField Ingresarteléfono;
    private javax.swing.JLabel Ingresoproveedores;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Ruc;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton ingresar;
    private javax.swing.JTextField ingresardireccion;
    private javax.swing.JTextField ingresarruc;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel telefono;
    // End of variables declaration//GEN-END:variables
}
